### PR TITLE
IL-678 Update `image_sku`

### PR DESCRIPTION
**Pull request by thomashashi**
See IL-678 and https://github.com/hashicorp/se-workshop-hashicat-app/pull/7 for details

### CODE REVIEW

**Review by thomashashi — COMMENTED** [review]
LGTM

**Review by gcastill0 — CHANGES_REQUESTED** [review]
I think we need to change the image as well.

```
variable "image_offer" {
  description = "Name of the offer (az vm image list)"
  default     = "0001-com-ubuntu-server-jammy"
}
```

**Review by gcastill0 — APPROVED** [review]
My last comment should be ignore.

Ship it

**Comment by thomashashi** [comment]
> I think we need to change the image as well.
> 
> ```
> variable "image_offer" {
>   description = "Name of the offer (az vm image list)"
>   default     = "0001-com-ubuntu-server-jammy"
> }
> ```

This matches what we have in the commit in `se-workshop-hashicat-app` - https://github.com/hashicorp/se-workshop-hashicat-app/blob/6566ea2044e5212d3602584f0e55a16f9cc4dfb6/hashicat-azure/variables.tf#L32-L50:

```
variable "image_publisher" {
  description = "Name of the publisher of the image (az vm image list)"
  default     = "Canonical"
}


variable "image_offer" {
  description = "Name of the offer (az vm image list)"
  default     = "0001-com-ubuntu-server-jammy"
}


variable "image_sku" {
  description = "Image SKU to apply (az vm image list)"
  default     = "22_04-LTS-gen2"
}


variable "image_version" {
  description = "Version of the image to apply (az vm image list)"
  default     = "latest"
}
```

**Pull request merged**
